services:
  - type: web
    name: bitly-service
    env: docker
    plan: free
    region: oregon  # or frankfurt, singapore, etc.
    dockerfilePath: ./Dockerfile
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
